echo started
wget -m -p -E -k -K -np "https://github.com/wikimedia/apps-android-wikipedia/blob/master/app/src/main/java/org/wikipedia/feed/continuereading/LastPageReadTask.java" 
wget -m -p -E -k -K -np "https://github.com/paypal/squbs/blob/master/squbs-httpclient/src/test/java/org/squbs/httpclient/japi/EmployeeBean.java" 
wget -m -p -E -k -K -np "https://github.com/impetus-opensource/Kundera/blob/master/src/kundera-cassandra/cassandra-core/src/test/java/com/impetus/client/cassandra/thrift/cql/CQLUser.java" 
wget -m -p -E -k -K -np "https://github.com/GlowstoneMC/Glowstone/blob/master/src/main/java/net/glowstone/entity/GlowAgeable.java" 
wget -m -p -E -k -K -np "https://github.com/eclipse/eclipse-collections-kata/blob/master/pet-kata/src/main/java/org/eclipse/collections/petkata/Pet.java" 
wget -m -p -E -k -K -np "https://github.com/outbrain/ob1k/blob/master/ob1k-cache/src/test/java/com/outbrain/ob1k/cache/memcache/folsom/Person.java" 
wget -m -p -E -k -K -np "https://github.com/apache/ignite/blob/master/modules/indexing/src/test/java/org/apache/ignite/internal/processors/cache/SqlFieldsQuerySelfTest.java" 
wget -m -p -E -k -K -np "https://github.com/hprose/hprose-java/blob/master/example/exam/server/src/main/java/hprose/exam/server/User.java" 
wget -m -p -E -k -K -np "https://github.com/droolsjbpm/kie-wb-distributions/blob/master/kie-wb-smoke-tests/kie-wb-smoke-tests-main/src/test/java/org/kie/tests/Person.java" 
wget -m -p -E -k -K -np "https://github.com/automenta/narchy/blob/master/logic/src/main/java/nars/learn/gng/Connection.java" 