echo started
wget -m -p -E -k -K -np "https://github.com/IMS-MAXIMS/openMAXIMS/blob/master/Source Library/openmaxims_workspace-archive/DTOClients/src/ims/dto/client/Episodelist.java" 
wget -m -p -E -k -K -np "https://github.com/IMS-MAXIMS/openMAXIMS/blob/master/Source Library/openmaxims_workspace-archive/DTOClients/src/ims/dto/client/Booklist.java" 
wget -m -p -E -k -K -np "https://github.com/IMS-MAXIMS/openMAXIMS/blob/master/Source Library/openmaxims_workspace-archive/DTOClients/src/ims/dto/client/Booklist.java" 
wget -m -p -E -k -K -np "https://github.com/oopcell/AvoinApotti/blob/master/Source Library/openmaxims_workspace/DomainObjects/src/ims/core/patient/domain/objects/MergedPatient.java" 
wget -m -p -E -k -K -np "https://github.com/netroby/jdk9-dev/blob/master/langtools/test/tools/javac/lambda/methodReference/MethodRef5.java" 
wget -m -p -E -k -K -np "https://github.com/apache/tapestry5/blob/master/tapestry-core/src/test/java/org/apache/tapestry5/internal/DataBean.java" 
wget -m -p -E -k -K -np "https://github.com/myblockchain/myblockchain/blob/master/storage/ndb/clusterj/clusterj-jpatest/src/main/java/com/mysql/clusterj/jpatest/LazyTest.java" 
wget -m -p -E -k -K -np "https://github.com/webscalesql/webscalesql-5.6/blob/master/storage/ndb/clusterj/clusterj-jpatest/src/main/java/com/mysql/clusterj/jpatest/model/Embedded.java" 
wget -m -p -E -k -K -np "https://github.com/helun/Ektorp/blob/master/org.ektorp/src/test/java/org/ektorp/impl/StdCouchDbConnectorTest.java" 
wget -m -p -E -k -K -np "https://github.com/vogellacompany/vogella/blob/master/com.vogella.javastarter.exercises1/src/com/vogella/javastarter/exercises1/Person.java" 
wget -m -p -E -k -K -np "https://github.com/gridgain/apache-ignite/blob/master/modules/indexing/src/test/java/org/apache/ignite/internal/processors/cache/GridCacheAbstractFieldsQuerySelfTest.java" 
wget -m -p -E -k -K -np "https://github.com/mplushnikov/lombok-intellij-plugin/blob/master/testData/after/builder/BuilderPredefined.java" 
wget -m -p -E -k -K -np "https://github.com/mplushnikov/lombok-intellij-plugin/blob/master/testData/after/builder/BuilderPredefined.java" 
