echo started
wget -m -p -E -k -K -np "https://raw.githubusercontent.com/facebook/fbthrift/master/thrift/compiler/test/fixtures/optionals/gen-java/Person.java" 
wget -m -p -E -k -K -np "https://raw.githubusercontent.com/Sellegit/j2objc/master/guava/sources/com/google/common/net/HttpHeaders.java" 
wget -m -p -E -k -K -np "https://raw.githubusercontent.com/wingy/Exodus/master/Clover/app/src/main/java/ch/boye/httpclientandroidlib/client/cache/HeaderConstants.java" 
wget -m -p -E -k -K -np "https://raw.githubusercontent.com/jaibeermalik/elasticsearch-tutorial/master/src/main/java/org/jai/search/data/SampleDataGenerator.java" 
wget -m -p -E -k -K -np "https://raw.githubusercontent.com/IMS-MAXIMS/openMAXIMS/master/Source Library/openmaxims_workspace-archive/DTOClients/src/ims/dto/client/Outpat.java" 
wget -m -p -E -k -K -np "https://raw.githubusercontent.com/IMS-MAXIMS/openMAXIMS/master/Source Library/openmaxims_workspace-archive/DTOClients/src/ims/dto/client/Outpat.java" 
wget -m -p -E -k -K -np "https://raw.githubusercontent.com/IMS-MAXIMS/openMAXIMS/master/Source Library/openmaxims_workspace-archive/DTOClients/src/ims/dto/client/Episodelist.java" 
wget -m -p -E -k -K -np "https://raw.githubusercontent.com/IMS-MAXIMS/openMAXIMS/master/Source Library/openmaxims_workspace-archive/DTOClients/src/ims/dto/client/Episodelist.java" 
wget -m -p -E -k -K -np "https://raw.githubusercontent.com/IMS-MAXIMS/openMAXIMS/master/Source Library/openmaxims_workspace-archive/DTOClients/src/ims/dto/client/Booklist.java" 
wget -m -p -E -k -K -np "https://raw.githubusercontent.com/IMS-MAXIMS/openMAXIMS/master/Source Library/openmaxims_workspace-archive/DTOClients/src/ims/dto/client/Booklist.java" 
wget -m -p -E -k -K -np "https://raw.githubusercontent.com/oopcell/AvoinApotti/master/Source Library/openmaxims_workspace/DomainObjects/src/ims/core/patient/domain/objects/MergedPatient.java" 
wget -m -p -E -k -K -np "https://raw.githubusercontent.com/happyjack27/autoredistrict/master/src/solutions/Settings.java" 
wget -m -p -E -k -K -np "https://raw.githubusercontent.com/wangqi/gameserver/master/bootstrap/src/main/java/com/xinqihd/sns/gameserver/config/Constant.java" 
wget -m -p -E -k -K -np "https://raw.githubusercontent.com/redfish64/TinyTravelTracker/master/app/src/main/java/org/bouncycastle/asn1/eac/EACTags.java" 
wget -m -p -E -k -K -np "https://raw.githubusercontent.com/pac4j/pac4j/master/pac4j-oauth/src/main/java/org/pac4j/oauth/profile/vk/VkAttributesDefinition.java" 
wget -m -p -E -k -K -np "https://raw.githubusercontent.com/lenbo-ma/jfinal-api-scaffold/master/src/main/java/com/mlongbo/jfinal/model/User.java" 
wget -m -p -E -k -K -np "https://raw.githubusercontent.com/scoophealth/oscar/master/src/main/java/com/quatro/dao/security/SecProviderDao.java" 
wget -m -p -E -k -K -np "https://raw.githubusercontent.com/pac4j/pac4j/master/pac4j-oauth/src/main/java/org/pac4j/oauth/profile/strava/StravaAttributesDefinition.java" 